### ISSUE TITLE
Please add me "Ray Pereda" to list of contributors on http://bigocheatsheet.com/

### ISSUE THREAD

**Issue by raypereda** [ericdrowell/BigOCheatSheet#102]
@ericdrowell 
I made a contribution via this PR: https://github.com/ericdrowell/BigOCheatSheet/pull/81

Please add me if you don't mine to the list of contributors.

BigOCheatSheet is a great idea, and glad to be a small part of it.

**Comment by ericdrowell** [comment]
So sorry I missed this.  I periodically sync up the contributors list with the github contributors graph, and somehow your name was lost.  It's there now.
