### ISSUE TITLE
Color keys

### ISSUE THREAD

**Issue by qpleple** [ericdrowell/BigOCheatSheet#14]
Coloring is hard to define.

For eg, finding the shortest-path in a graph with negative edges:
* Dijkstra is fast, takes O((V+E) log V) but does work with negative edges.
* Bellman-Ford is O(VE), it's way slower than Dijkstra.

Would you put Bellman-Ford in green because it's the fastest you can do in that situation? Or in red because it's slower than Dijkstra?

How about absolute colors for each of the following categories?
* white: constant-time, O(1)
* blue: sub-linear, like O(log n) or O(sqrt n)
* green: linear, O(n)
* yellow: [quasilinear](http://en.wikipedia.org/wiki/Time_complexity#Linearithmic.2Fquasilinear_time), like O(n log n)
* red: higher, like O(n^2), O(n^2 log n), O(n^3)

I don't think you would ever want to list an exponential time algorithm, O(2^n), O(n!), O(n^n), so no color needed

**Comment by ericdrowell** [comment]
agreed, this is where the coloring has started to head.  There's still a little more work to do to make the coloring more consistent.  Will work on these more over the weekend.
