### ISSUE TITLE
Add section headers to nav bar

### ISSUE THREAD

**Issue by albertyw** [ericdrowell/BigOCheatSheet#16]
Currently, the nav bar has 
Searching
Sorting
Graph
Comments

It's missing Data Structures and there's a bit of name collision between graph algorithms and the Big-O complexity graph.

**Comment by ericdrowell** [comment]
Thanks for the suggestion.  To cleanup the header, I actually decided to remove all of the nav links, and replace them with a Download PDF button.  It's easy enough to scroll down and see what sections are available.
