### ISSUE TITLE
Use GitHub Pages + CNAME

### ISSUE THREAD

**Issue by jdavis** [ericdrowell/BigOCheatSheet#8]
One suggestion is to use GitHub pages and just add a CNAME to your repository. If you create a branch called gh-pages, it will automatically update the website. This way you won't have to worry about keeping the server and code in sync.

Read more about GitHub Pages [here](https://help.github.com/categories/20/articles).

**Comment by bbodenmiller** [comment]
+1

**Comment by ericdrowell** [comment]
Thanks for the suggestion, but I prefer hosting the page myself.
