### ISSUE TITLE
Add O(nlog^n) to Chart

### ISSUE THREAD

**Issue by caspar** [ericdrowell/BigOCheatSheet#87]
Can we replace the existing image with the one below? 
__Shell sort__ has time complexity `O((nlogn)^2)` in its average and worst case, but this function is not included in the chart provided. 
![big-o-complexity](https://cloud.githubusercontent.com/assets/5422063/7675024/e4189e58-fd00-11e4-9622-a48509980cf4.png)

_Here's an iframe linked to an interactive version:_
```
<iframe width="840" height="466" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/1V6hJ9R0Tx9JMa0pEUq2TTkMFCkVO00vdusFFUYLmhbw/pubchart?oid=1753507166&amp;format=interactive"></iframe>
```

  
@caspar

**Comment by ericdrowell** [comment]
Thanks for creating a google chart version, this looks a lot better than the one I had before.  Right now I'm using a hand crafted SVG version with inline labels rather than a legend, and I intend for the colors to match up with the page colors (red yellow green).  

Closing this ticket for now.
